/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hishamhamid (https://sketchfab.com/hishamhamid)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-3d-earth-model-439de097307b4a37ac626a2a5f990e81
title: (FREE) 3D Earth Model
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useSpring, a } from '@react-spring/three'

type GLTFResult = GLTF & {
  nodes: {
    pSphere1_lambert3_0: THREE.Mesh
  }
  materials: {
    lambert3: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { scale } = props

  const animatedProps = useSpring({
    rotation: [0, Math.PI * 2, 0],
    from: { rotation: [0, 0, 0] },
    config: { duration: 40000 },
    loop: { reverse: true },
  })

  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/earth.glb') as GLTFResult

  return (
    <a.group ref={group} {...props} {...animatedProps} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={8.06}>
            <mesh geometry={nodes.pSphere1_lambert3_0.geometry} material={materials.lambert3} />
          </group>
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('/earth.glb')
